# Generated by Django 5.1.6 on 2025-03-17 14:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('resource_requirements', models.JSONField(blank=True, default=dict)),
                ('sustainability_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='building_templates/')),
                ('upgrade_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('produces_resource', models.CharField(blank=True, max_length=50, null=True)),
                ('production_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Eco City', max_length=100)),
                ('sustainability_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('funds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grid_width', models.PositiveIntegerField(default=5)),
                ('grid_height', models.PositiveIntegerField(default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='city', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CityBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('upgrade_level', models.PositiveIntegerField(default=1)),
                ('built_at', models.DateTimeField(auto_now_add=True)),
                ('last_collected', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='city_builder.city')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='city_builder.buildingtemplate')),
            ],
            options={
                'ordering': ['x', 'y'],
                'unique_together': {('city', 'x', 'y')},
            },
        ),
    ]
