# Generated by Django 5.1.6 on 2025-03-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bing_board',
            field=models.JSONField(default=list),
        ),
    ]
