# Generated by Django 5.1.6 on 2025-02-28 16:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_gdpr_consent_userprofile_tc_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currency_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
