# Generated by Django 5.1.6 on 2025-03-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_bing_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bing_board',
            new_name='bingo_board',
        ),
    ]
