# Generated by Django 5.1.5 on 2025-03-17 15:46

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('growth_duration', models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Time required for full growth')),
                ('is_harvested', models.BooleanField(default=False)),
                ('seed', models.ForeignKey(help_text="Seed used for planting; should be an item of type 'seed'", on_delete=django.db.models.deletion.CASCADE, to='crates.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_plants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GardenPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Plot', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_plant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plot', to='garden.gardenplant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_plots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
