# Generated by Django 5.1.6 on 2025-03-17 14:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_donated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='BlackjackGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deck', models.JSONField(default=list)),
                ('player_hand', models.JSONField(default=list)),
                ('dealer_hand', models.JSONField(default=list)),
                ('result', models.CharField(choices=[('in_progress', 'In Progress'), ('win', 'Win'), ('lose', 'Lose'), ('push', 'Push')], default='in_progress', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiceGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bet_type', models.CharField(choices=[('exact', 'Exact Number'), ('odd_even', 'Odd or Even'), ('high_low', 'High or Low')], default='exact', max_length=10)),
                ('prediction', models.IntegerField(blank=True, null=True)),
                ('roll_result', models.IntegerField(blank=True, null=True)),
                ('win', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GreenFundContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_donated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouletteGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bet_type', models.CharField(choices=[('number', 'Number'), ('color', 'Color'), ('odd_even', 'Odd/Even'), ('low_high', 'Low/High')], default='number', max_length=10)),
                ('prediction', models.CharField(help_text='Enter your prediction (e.g. a number, red/black, odd/even, low/high)', max_length=10)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('win', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
