# Generated by Django 5.1.6 on 2025-03-17 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('co2_reduction', models.FloatField()),
                ('gdp_impact', models.FloatField()),
                ('cost', models.FloatField(default=10.0)),
            ],
        ),
        migrations.CreateModel(
            name='PowerUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('effect_type', models.CharField(choices=[('co2_reduction', 'CO₂ Reduction'), ('gdp_boost', 'GDP Boost'), ('policy_boost', 'Policy Effect x2'), ('block_opponent', 'Block Opponent')], max_length=50)),
                ('effect_value', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClimateDuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('player_one_budget', models.FloatField(default=100.0)),
                ('player_two_budget', models.FloatField(default=100.0)),
                ('player_one_co2', models.FloatField(default=100.0)),
                ('player_two_co2', models.FloatField(default=100.0)),
                ('player_one_gdp', models.FloatField(default=100.0)),
                ('player_two_gdp', models.FloatField(default=100.0)),
                ('current_turn', models.IntegerField(default=1)),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_duels_as_p1', to=settings.AUTH_USER_MODEL)),
                ('player_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='climate_duels_as_p2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DuelTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_after_turn', models.FloatField()),
                ('gdp_after_turn', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate_duels.climateduel')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chosen_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climate_duels.policy')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPowerUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('powerup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate_duels.powerup')),
            ],
        ),
    ]
