# Generated by Django 5.1.5 on 2025-03-17 15:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_upgrade_cost', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Base currency cost for upgrading this building', max_digits=10)),
                ('blueprint_required', models.ForeignKey(blank=True, help_text='Blueprint required for constructing this building', limit_choices_to={'item_type': 'blueprint'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crates.item')),
                ('prerequisite', models.ForeignKey(blank=True, help_text='Building that must be built to unlock this building', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='farm.buildingtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.buildingtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingUpgradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_level', models.PositiveIntegerField()),
                ('new_level', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_history', to='farm.building')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingUpgradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(help_text='Upgrade level (starting at 1)')),
                ('upgrade_currency_cost', models.DecimalField(decimal_places=2, help_text='Currency cost required for this upgrade', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('blueprint_required', models.ForeignKey(blank=True, help_text='Optional blueprint required for this upgrade level', limit_choices_to={'item_type': 'blueprint'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crates.item')),
                ('building_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_levels', to='farm.buildingtemplate')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('building_template', 'level')},
            },
        ),
        migrations.CreateModel(
            name='BuildingUpgradeMaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.PositiveIntegerField(default=1, help_text='Quantity of this item required')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crates.item')),
                ('upgrade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='farm.buildingupgradelevel')),
            ],
        ),
    ]
