# Generated by Django 5.1.5 on 2025-02-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_two_factor_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='two_factor_enabled',
        ),
    ]
