# Generated by Django 5.1.6 on 2025-02-28 17:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketevent',
            name='companies_affected',
            field=models.ManyToManyField(blank=True, related_name='market_events', to='market.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='current_stock_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='sustainability_rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('5.0'), max_digits=3),
        ),
    ]
